### PR TITLE
Added password strength validation ( weak,medium,strong).

### PR DESCRIPTION
**Pull request by barkhayadav12**

### CODE REVIEW

**Comment by barkhayadav12** [comment]
Sign up:
signuppass
Login:
loginpass

**Comment by Gyanthakur** [comment]
> Sign up: signuppass Login: loginpass

not working properly 

re-run whole project and fix issue

**Comment by barkhayadav12** [comment]
Can you tell what changes do I have to make?

**Comment by Gyanthakur** [comment]
> Can you tell me what changes do I have to make?

when you run a project then go to the login or signup page directly,
without login or signup not go to the home page

**Comment by barkhayadav12** [comment]
I have made the changes as suggested. Please check.

**Pull request closed without merging**
